[files]
recent_files=/home/ishida/Dropbox/Projects/Setups/arch/post-installation.py;/home/ishida/Dropbox/Projects/Setups/arch/fishcfg.py;/home/ishida/Dropbox/Projects/Setups/arch/all.sh;/home/ishida/Dropbox/Projects/Setups/arch/setup.py;/home/ishida/Dropbox/Documents/Python/print_.py;/home/ishida/Dropbox/Documents/Python/demo.py;/run/media/ishida/Backups/Dropbox/Documents/Python/click_website_button.py;/home/ishida/Dropbox/Documents/Python/click_website_button.py;/home/ishida/Dropbox/Projects/Setups/geany/backupconfig.sh;/home/ishida/Dropbox/Projects/Setups/geany/setup.sh;
recent_projects=/home/ishida/Dropbox/Projects/Setups/arch/arch.geany;/home/ishida/Dropbox/Documents/Python/Python.geany;Arch;
current_page=0

[project]
session_file=/home/ishida/Dropbox/Projects/Setups/arch/arch.geany
project_file_path=/home/ishida/projects

[geany]
treeview_position=229
msgwindow_position=433
geometry=0;30;1366;710;1;
sidebar_page=1

[VTE]
last_dir=/home/ishida/Dropbox/Projects/Setups/arch

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=-1
position_find_y=-1
position_replace_x=-1
position_replace_y=-1
position_fif_x=391
position_fif_y=250

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
